#include "relay_init.hpp"

#include "relay_config.hpp"
#include "relay_database.hpp"
#include "relay_enrollment.hpp"
#include "relay_turn_credentials.hpp"

#include <heyaki/error.hpp>
#include <heyaki/password.hpp>
#include <heyaki/security.hpp>

#include <openssl/bio.h>
#include <openssl/evp.h>
#include <openssl/obj_mac.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <sodium.h>

#include <boost/asio/io_context.hpp>
#include <boost/asio/ip/host_name.hpp>
#include <boost/asio/ip/tcp.hpp>

#include <algorithm>
#include <array>
#include <cerrno>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <fstream>
#include <iostream>
#include <optional>
#include <string>
#include <vector>

#if !defined(_WIN32)
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <termios.h>
#include <unistd.h>
#endif

namespace heyaki {
namespace {

Error init_error(ErrorCode code, const char* detail,
                 std::optional<std::int64_t> underlying = std::nullopt) {
  return Error{code, "relay_init", detail, underlying};
}

// Baseline relay.conf emitted when no configuration exists (the same values
// as the getting-started minimal sample, with password enrollment enabled).
std::string baseline_config_text(const RelayInitOptions& options) {
  std::string text;
  text += "# Generated by heyaki-relay --init; every key is documented in\n";
  text += "# docs/configuration.md.\n";
  text += "listen_address = " + options.listen_address.value_or("0.0.0.0") + "\n";
  text += "listen_port = " + std::to_string(options.listen_port.value_or(8443U)) + "\n";
  text += "tls_certificate_file = certs/relay.crt\n";
  text += "tls_private_key_file = certs/relay.key\n";
  text += "database_file = relay.sqlite\n";
  text += "enrollment_mode = password\n";
  text += "enrollment_default_tenant = " + options.enrollment_tenant + "\n";
  return text;
}

std::string hex_encode(const std::array<std::byte, 32U>& bytes) {
  static constexpr char digits[] = "0123456789abcdef";
  std::string output;
  output.reserve(bytes.size() * 2U);
  for (const auto byte : bytes) {
    const auto value = std::to_integer<unsigned char>(byte);
    output.push_back(digits[value >> 4U]);
    output.push_back(digits[value & 0x0fU]);
  }
  return output;
}

bool regular_file_exists(const std::filesystem::path& path) {
  std::error_code error;
  const bool exists = std::filesystem::is_regular_file(path, error);
  return !error && exists;
}

void restrict_owner_permissions(const std::filesystem::path& path) {
  std::error_code error;
  std::filesystem::permissions(path,
                               std::filesystem::perms::owner_read |
                                   std::filesystem::perms::owner_write,
                               error);
}

std::string_view advertised_host(const std::vector<std::string>& san_entries,
                                 const RelayInitOptions& options) {
  if (!options.listen_address.has_value() || options.listen_address == "0.0.0.0" ||
      options.listen_address == "::") {
    for (const auto& entry : san_entries) {
      if (entry != "localhost" && entry != "127.0.0.1" && entry != "::1") {
        return entry;
      }
    }
    return "localhost";
  }
  return *options.listen_address;
}

Result<std::array<std::byte, 32U>> certificate_digest(
    const std::filesystem::path& certificate_file) {
  // PEM I/O goes through OpenSSL BIO, never FILE*: on Windows the FILE*-based
  // PEM helpers require an OPENSSL_Applink table the app/test builds do not
  // provide and abort at runtime (OPENSSL_Uplink ... no OPENSSL_Applink).
#if defined(_WIN32)
  BIO* file = BIO_new_file(certificate_file.string().c_str(), "rb");
#else
  BIO* file = BIO_new_file(certificate_file.c_str(), "rb");
#endif
  if (file == nullptr) {
    return Result<std::array<std::byte, 32U>>::failure(
        init_error(ErrorCode::configuration, "relay_init_certificate_unreadable"));
  }
  X509* certificate = PEM_read_bio_X509(file, nullptr, nullptr, nullptr);
  BIO_free(file);
  if (certificate == nullptr) {
    return Result<std::array<std::byte, 32U>>::failure(
        init_error(ErrorCode::configuration, "relay_init_certificate_unreadable"));
  }
  std::array<std::byte, 32U> digest{};
  const int matched = X509_digest(certificate, EVP_sha256(),
                                  reinterpret_cast<unsigned char*>(digest.data()),
                                  nullptr);
  X509_free(certificate);
  if (matched != 1) {
    return Result<std::array<std::byte, 32U>>::failure(
        init_error(ErrorCode::configuration, "relay_init_certificate_digest_failed"));
  }
  return Result<std::array<std::byte, 32U>>::success(digest);
}

// Minimal path-key reader for the bootstrap order: init needs the configured
// certificate/key/database paths BEFORE load_relay_config_file can validate
// the configuration (which requires the certificate to exist). Returns the
// configured values resolved against the config directory, falling back to
// the baseline names when a key is absent.
struct RelayConfigPathKeys {
  std::filesystem::path tls_certificate_file{"certs/relay.crt"};
  std::filesystem::path tls_private_key_file{"certs/relay.key"};
  std::filesystem::path database_file{"relay.sqlite"};
};

Result<RelayConfigPathKeys> read_config_path_keys(const std::filesystem::path& config_file) {
  std::ifstream input{config_file, std::ios::binary};
  if (!input) {
    return Result<RelayConfigPathKeys>::failure(
        init_error(ErrorCode::configuration, "relay_init_config_unreadable", errno));
  }
  RelayConfigPathKeys keys;
  auto trim = [](std::string value) {
    const auto first = value.find_first_not_of(" \t");
    if (first == std::string::npos) {
      return std::string{};
    }
    const auto last = value.find_last_not_of(" \t");
    return value.substr(first, last - first + 1U);
  };
  std::string line;
  while (std::getline(input, line)) {
    const auto separator = line.find('=');
    if (separator == std::string::npos) {
      continue;
    }
    const auto key = trim(line.substr(0U, separator));
    const auto value = trim(line.substr(separator + 1U));
    if (key == "tls_certificate_file") {
      keys.tls_certificate_file = std::filesystem::path{value};
    } else if (key == "tls_private_key_file") {
      keys.tls_private_key_file = std::filesystem::path{value};
    } else if (key == "database_file" && value != ":memory:") {
      keys.database_file = std::filesystem::path{value};
    }
  }
  if (keys.tls_certificate_file.is_relative()) {
    keys.tls_certificate_file = config_file.parent_path() / keys.tls_certificate_file;
  }
  if (keys.tls_private_key_file.is_relative()) {
    keys.tls_private_key_file = config_file.parent_path() / keys.tls_private_key_file;
  }
  if (keys.database_file.is_relative()) {
    keys.database_file = config_file.parent_path() / keys.database_file;
  }
  return Result<RelayConfigPathKeys>::success(std::move(keys));
}

}  // namespace

Result<std::vector<std::string>> collect_local_san_entries() {
  boost::system::error_code error;
  std::vector<std::string> entries;
  auto hostname = boost::asio::ip::host_name(error);
  if (!error && !hostname.empty()) {
    entries.push_back(std::move(hostname));
  }
  if (!hostname.empty()) {
    boost::asio::io_context context;
    boost::asio::ip::tcp::resolver resolver{context};
    auto resolved = resolver.resolve(hostname, "0", error);
    if (!error) {
      for (const auto& entry : resolved) {
        const auto address = entry.endpoint().address();
        if (address.is_loopback() || address.is_multicast()) {
          continue;
        }
        const std::string text = address.to_string();
        const bool duplicate =
            std::any_of(entries.begin(), entries.end(),
                        [&](const std::string& existing) { return existing == text; });
        if (!duplicate) {
          entries.push_back(text);
        }
      }
    }
  }
  entries.push_back("localhost");
  entries.push_back("127.0.0.1");
  entries.push_back("::1");
  if (entries.size() <= 3U) {
    return Result<std::vector<std::string>>::failure(
        init_error(ErrorCode::configuration, "relay_init_san_discovery_failed"));
  }
  return Result<std::vector<std::string>>::success(std::move(entries));
}

Result<std::array<std::byte, 32U>> generate_self_signed_relay_certificate(
    const std::filesystem::path& certificate_file,
    const std::filesystem::path& private_key_file,
    const std::vector<std::string>& san_entries) {
  if (san_entries.empty()) {
    return Result<std::array<std::byte, 32U>>::failure(
        init_error(ErrorCode::configuration, "relay_init_san_entries_invalid"));
  }
  std::string san_text;
  for (std::size_t index = 0U; index < san_entries.size(); ++index) {
    if (index != 0U) {
      san_text += ", ";
    }
    // Address literals get the IP SAN type; everything else is DNS.
    if (san_entries[index].find(':') != std::string::npos ||
        san_entries[index].find_first_not_of("0123456789.") == std::string::npos) {
      san_text += "IP:" + san_entries[index];
    } else {
      san_text += "DNS:" + san_entries[index];
    }
  }
  const std::string common_name = san_entries.front();

  EVP_PKEY* key = nullptr;
  {
    // Classic ctx keygen: same code path across OpenSSL 3.x minor drift and
    // the only EC keygen variant that works uniformly with the pinned
    // runtimes.
    EVP_PKEY_CTX* key_context = EVP_PKEY_CTX_new_id(EVP_PKEY_EC, nullptr);
    if (key_context == nullptr || EVP_PKEY_keygen_init(key_context) <= 0 ||
        EVP_PKEY_CTX_set_ec_paramgen_curve_nid(key_context,
                                               NID_X9_62_prime256v1) <= 0 ||
        EVP_PKEY_keygen(key_context, &key) <= 0) {
      EVP_PKEY_CTX_free(key_context);
      return Result<std::array<std::byte, 32U>>::failure(
          init_error(ErrorCode::internal, "relay_init_keygen_failed"));
    }
    EVP_PKEY_CTX_free(key_context);
  }
  X509* certificate = X509_new();
  if (certificate == nullptr) {
    EVP_PKEY_free(key);
    return Result<std::array<std::byte, 32U>>::failure(
        init_error(ErrorCode::internal, "relay_init_x509_alloc_failed"));
  }
  std::array<std::byte, 32U> fingerprint{};
  auto fail = [&](const char* detail) {
    X509_free(certificate);
    EVP_PKEY_free(key);
    sodium_memzero(fingerprint.data(), fingerprint.size());
    return Result<std::array<std::byte, 32U>>::failure(
        init_error(ErrorCode::internal, detail));
  };

  if (X509_set_version(certificate, 2) != 1) {
    return fail("relay_init_x509_version_failed");
  }
  BIGNUM* serial_bignum = BN_new();
  ASN1_INTEGER* serial_number = ASN1_INTEGER_new();
  if (serial_bignum == nullptr || serial_number == nullptr ||
      BN_rand(serial_bignum, 63, -1, 0) != 1 ||
      BN_to_ASN1_INTEGER(serial_bignum, serial_number) == nullptr ||
      X509_set_serialNumber(certificate, serial_number) != 1) {
    BN_free(serial_bignum);
    ASN1_INTEGER_free(serial_number);
    return fail("relay_init_x509_serial_failed");
  }
  BN_free(serial_bignum);
  ASN1_INTEGER_free(serial_number);
  if (X509_set_pubkey(certificate, key) != 1) {
    return fail("relay_init_x509_pubkey_failed");
  }
  X509_NAME* subject = X509_get_subject_name(certificate);
  if (subject == nullptr ||
      X509_NAME_add_entry_by_txt(subject, "CN", MBSTRING_ASC,
                                 reinterpret_cast<const unsigned char*>(
                                     common_name.c_str()),
                                 -1, -1, 0) != 1) {
    return fail("relay_init_x509_subject_failed");
  }
  auto now = std::time(nullptr);
  if (X509_time_adj_ex(X509_getm_notBefore(certificate), 0, -60 * 60, &now) == nullptr ||
      X509_time_adj_ex(X509_getm_notAfter(certificate), 3650, 0, &now) == nullptr) {
    return fail("relay_init_x509_validity_failed");
  }
  if (X509_set_issuer_name(certificate, subject) != 1) {
    return fail("relay_init_x509_issuer_failed");
  }
  X509V3_CTX extension_context;
  X509V3_set_ctx(&extension_context, certificate, nullptr, nullptr, nullptr, 0);
  X509_EXTENSION* san = X509V3_EXT_conf_nid(nullptr, &extension_context,
                                            NID_subject_alt_name, san_text.c_str());
  if (san == nullptr) {
    return fail("relay_init_x509_san_failed");
  }
  const int san_added = X509_add_ext(certificate, san, -1);
  X509_EXTENSION_free(san);
  if (san_added != 1) {
    return fail("relay_init_x509_san_add_failed");
  }
  X509_EXTENSION* basic_constraints = X509V3_EXT_conf_nid(
      nullptr, &extension_context, NID_basic_constraints, "critical,CA:TRUE");
  if (basic_constraints == nullptr) {
    return fail("relay_init_x509_constraints_failed");
  }
  const int constraints_added = X509_add_ext(certificate, basic_constraints, -1);
  X509_EXTENSION_free(basic_constraints);
  if (constraints_added != 1) {
    return fail("relay_init_x509_constraints_add_failed");
  }
  if (X509_sign(certificate, key, EVP_sha256()) == 0) {
    return fail("relay_init_x509_sign_failed");
  }
  if (X509_digest(certificate, EVP_sha256(),
                  reinterpret_cast<unsigned char*>(fingerprint.data()),
                  nullptr) != 1) {
    return fail("relay_init_x509_digest_failed");
  }

#if defined(_WIN32)
  BIO* key_file = BIO_new_file(private_key_file.string().c_str(), "wb");
  if (key_file == nullptr) {
    return fail("relay_init_key_write_failed");
  }
#else
  // POSIX keeps the race-safe exclusive create with owner-only mode; the
  // descriptor is wrapped as a BIO so the same bio PEM writer serves both
  // platforms.
  const int key_fd = ::open(private_key_file.c_str(),
                            O_WRONLY | O_CREAT | O_EXCL | O_CLOEXEC, 0600);
  if (key_fd < 0) {
    return fail("relay_init_key_write_failed");
  }
  std::FILE* key_stream = ::fdopen(key_fd, "wb");
  if (key_stream == nullptr) {
    ::close(key_fd);
    return fail("relay_init_key_write_failed");
  }
  BIO* key_file = BIO_new_fp(key_stream, BIO_CLOSE);
  if (key_file == nullptr) {
    std::fclose(key_stream);
    return fail("relay_init_key_write_failed");
  }
#endif
  if (PEM_write_bio_PrivateKey(key_file, key, nullptr, nullptr, 0, nullptr,
                               nullptr) != 1) {
    BIO_free_all(key_file);
    return fail("relay_init_key_write_failed");
  }
  BIO_free_all(key_file);
#if defined(_WIN32)
  restrict_owner_permissions(private_key_file);
#endif

#if defined(_WIN32)
  BIO* cert_file = BIO_new_file(certificate_file.string().c_str(), "wb");
#else
  BIO* cert_file = BIO_new_file(certificate_file.c_str(), "wb");
#endif
  if (cert_file == nullptr) {
    return fail("relay_init_cert_write_failed");
  }
  if (PEM_write_bio_X509(cert_file, certificate) != 1) {
    BIO_free_all(cert_file);
    return fail("relay_init_cert_write_failed");
  }
  BIO_free_all(cert_file);

  X509_free(certificate);
  EVP_PKEY_free(key);
  return Result<std::array<std::byte, 32U>>::success(fingerprint);
}

Result<std::string> generate_turn_secret() {
  static constexpr std::string_view alphabet =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  std::string secret;
  secret.reserve(40U);
  for (int index = 0; index < 40; ++index) {
    secret.push_back(
        alphabet[randombytes_uniform(static_cast<std::uint32_t>(alphabet.size()))]);
  }
  auto valid = validate_turn_secret(secret);
  if (!valid) {
    sodium_memzero(secret.data(), secret.size());
    return Result<std::string>::failure(
        init_error(ErrorCode::internal, "relay_init_turn_secret_invalid"));
  }
  return Result<std::string>::success(std::move(secret));
}

Result<std::string> read_owner_password_file(
    const std::filesystem::path& password_file) {
  std::ifstream input{password_file, std::ios::binary};
  if (!input) {
    return Result<std::string>::failure(init_error(ErrorCode::configuration,
                                                   "relay_init_password_file_unreadable",
                                                   errno));
  }
  std::string line;
  std::getline(input, line);
  if (!line.empty() && line.back() == '\r') {
    line.pop_back();
  }
  if (line.empty() || line.size() > enrollment_password_max_bytes) {
    sodium_memzero(line.data(), line.size());
    return Result<std::string>::failure(
        init_error(ErrorCode::configuration, "relay_init_password_file_invalid"));
  }
  return Result<std::string>::success(std::move(line));
}

Result<std::string> prompt_owner_password() {
#if defined(_WIN32)
  return Result<std::string>::failure(init_error(
      ErrorCode::configuration, "relay_init_interactive_unsupported_use_password_file"));
#else
  termios saved{};
  if (::tcgetattr(STDIN_FILENO, &saved) != 0) {
    return Result<std::string>::failure(
        init_error(ErrorCode::configuration, "relay_init_terminal_unavailable", errno));
  }
  auto read_hidden = [&](const char* prompt) -> Result<std::string> {
    std::fputs(prompt, stdout);
    std::fflush(stdout);
    termios hidden = saved;
    hidden.c_lflag &= static_cast<tcflag_t>(~(ECHO | ECHONL));
    if (::tcsetattr(STDIN_FILENO, TCSAFLUSH, &hidden) != 0) {
      return Result<std::string>::failure(init_error(ErrorCode::configuration,
                                                     "relay_init_terminal_unavailable",
                                                     errno));
    }
    std::string line;
    int character;
    while ((character = std::fgetc(stdin)) != EOF && character != '\n') {
      if (line.size() < enrollment_password_max_bytes) {
        line.push_back(static_cast<char>(character));
      }
    }
    (void)::tcsetattr(STDIN_FILENO, TCSAFLUSH, &saved);
    std::fputc('\n', stdout);
    if (character == EOF && line.empty()) {
      sodium_memzero(line.data(), line.size());
      return Result<std::string>::failure(
          init_error(ErrorCode::configuration, "relay_init_password_read_failed"));
    }
    return Result<std::string>::success(std::move(line));
  };
  for (int attempt = 0; attempt < 3; ++attempt) {
    auto first = read_hidden("Set the relay enrollment password: ");
    if (!first) {
      return first;
    }
    auto second = read_hidden("Confirm the relay enrollment password: ");
    if (!second) {
      sodium_memzero(first.value_if()->data(), first.value_if()->size());
      return second;
    }
    if (*first.value_if() == *second.value_if()) {
      sodium_memzero(second.value_if()->data(), second.value_if()->size());
      return first;
    }
    sodium_memzero(first.value_if()->data(), first.value_if()->size());
    sodium_memzero(second.value_if()->data(), second.value_if()->size());
    std::fputs("Passwords do not match; try again.\n", stdout);
  }
  return Result<std::string>::failure(
      init_error(ErrorCode::configuration, "relay_init_password_mismatch"));
#endif
}

Result<void> run_relay_init(const RelayInitOptions& options) {
  if (options.enrollment_tenant.empty() || options.enrollment_tenant.size() > 128U) {
    return Result<void>::failure(
        init_error(ErrorCode::configuration, "relay_init_tenant_invalid"));
  }
  const auto config_directory = options.config_file.parent_path();

  // 1. Configuration (never overwrite).
  if (regular_file_exists(options.config_file)) {
    std::cout << "heyaki-relay --init: using existing config " << options.config_file
              << "\n";
  } else {
    std::error_code error;
    std::filesystem::create_directories(config_directory, error);
    std::ofstream output{options.config_file, std::ios::binary};
    if (!output) {
      return Result<void>::failure(
          init_error(ErrorCode::configuration, "relay_init_config_write_failed", errno));
    }
    output << baseline_config_text(options);
    output.close();
    if (!output) {
      return Result<void>::failure(
          init_error(ErrorCode::configuration, "relay_init_config_write_failed", errno));
    }
    std::cout << "heyaki-relay --init: wrote config " << options.config_file << "\n";
  }

  // 2. TLS certificate (never overwrite). Path keys are read directly so the
  // certificate can be generated before the strict config validation runs.
  auto path_keys = read_config_path_keys(options.config_file);
  if (!path_keys) {
    return Result<void>::failure(*path_keys.error_if());
  }
  auto certificate_file = path_keys.value_if()->tls_certificate_file;
  auto private_key_file = path_keys.value_if()->tls_private_key_file;
  if (options.tls_certificate_file) {
    certificate_file = *options.tls_certificate_file;
  }
  if (options.tls_private_key_file) {
    private_key_file = *options.tls_private_key_file;
  }
  auto san_entries = collect_local_san_entries();
  if (!san_entries) {
    return Result<void>::failure(*san_entries.error_if());
  }
  if (regular_file_exists(certificate_file)) {
    std::cout << "heyaki-relay --init: using existing TLS certificate "
              << certificate_file << "\n";
  } else {
    std::error_code error;
    std::filesystem::create_directories(certificate_file.parent_path(), error);
    auto generated = generate_self_signed_relay_certificate(
        certificate_file, private_key_file, *san_entries.value_if());
    if (!generated) {
      return Result<void>::failure(*generated.error_if());
    }
    std::cout << "heyaki-relay --init: generated self-signed certificate "
              << certificate_file << "\n";
  }
  auto pin = certificate_digest(certificate_file);
  if (!pin) {
    return Result<void>::failure(*pin.error_if());
  }

  // 3. Owner enrollment password: Argon2id verifier straight into the relay
  // database; the plaintext never lands on disk.
  auto config = load_relay_config_file(options.config_file);
  if (!config) {
    return Result<void>::failure(*config.error_if());
  }
  auto database_file = path_keys.value_if()->database_file;
  if (options.database_file) {
    database_file = *options.database_file;
  }
  auto database = RelayDatabase::open(database_file);
  if (!database) {
    return Result<void>::failure(*database.error_if());
  }
  auto existing_password = database.value_if()->enrollment_password_verifier();
  if (!existing_password) {
    return Result<void>::failure(*existing_password.error_if());
  }
  std::optional<std::string> password;
  bool interactive_password = false;
  if (options.password_file) {
    auto from_file = read_owner_password_file(*options.password_file);
    if (!from_file) {
      return Result<void>::failure(*from_file.error_if());
    }
    password = std::move(*from_file.value_if());
    std::cout << "heyaki-relay --init: password read from " << *options.password_file
              << " (delete the file once provisioning is done)\n";
  } else if (const char* from_environment = std::getenv("HEYAKI_INIT_PASSWORD");
             from_environment != nullptr && from_environment[0] != '\0') {
    password = std::string{from_environment};
    std::cout << "heyaki-relay --init: password read from HEYAKI_INIT_PASSWORD\n";
  } else {
    auto prompted = prompt_owner_password();
    if (!prompted) {
      if (!existing_password.value_if()->has_value()) {
        return Result<void>::failure(*prompted.error_if());
      }
      std::cout << "heyaki-relay --init: keeping the existing enrollment password\n";
    } else {
      password = std::move(*prompted.value_if());
      interactive_password = true;
    }
  }
  if (password.has_value()) {
    // Enforce the password policy on the human-chosen password up front (the
    // verifier below is computed over the derived proof, which would
    // otherwise bypass the policy check inside create_password_verifier).
    auto policy_ok = validate_password_policy(*password);
    if (!policy_ok) {
      sodium_memzero(password->data(), password->size());
      std::cerr << "heyaki-relay --init: " << policy_ok.error_if()->safe_detail() << "\n";
      return Result<void>::failure(*policy_ok.error_if());
    }
    auto parameters = calibrate_password_parameters();
    if (!parameters) {
      sodium_memzero(password->data(), password->size());
      return Result<void>::failure(*parameters.error_if());
    }
    // The verifier is computed over the hex of the relay-bound proof (exactly
    // what enrolling clients present and what the enrollment service
    // verifies), not over the plaintext password: the relay never stores — or
    // hashes — the password itself.
    auto proof = derive_enrollment_password_proof(*password, *pin.value_if());
    sodium_memzero(password->data(), password->size());
    if (!proof) {
      return Result<void>::failure(*proof.error_if());
    }
    static constexpr char digits[] = "0123456789abcdef";
    std::string proof_hex;
    proof_hex.reserve(proof.value_if()->size() * 2U);
    for (const auto byte : *proof.value_if()) {
      const auto value = std::to_integer<unsigned char>(byte);
      proof_hex.push_back(digits[value >> 4U]);
      proof_hex.push_back(digits[value & 0x0fU]);
    }
    sodium_memzero(proof.value_if()->data(), proof.value_if()->size());
    auto verifier = create_password_verifier(proof_hex, *parameters.value_if());
    sodium_memzero(proof_hex.data(), proof_hex.size());
    if (!verifier) {
      return Result<void>::failure(*verifier.error_if());
    }
    RelayEnrollmentPasswordRecord record;
    record.format_version = verifier.value_if()->format_version;
    record.kdf_operations =
        static_cast<std::uint32_t>(verifier.value_if()->parameters.operations);
    record.kdf_memory_kib = static_cast<std::uint32_t>(
        verifier.value_if()->parameters.memory_bytes / 1024U);
    record.encoded = verifier.value_if()->encoded;
    record.updated_unix_milliseconds =
        static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(
                                       std::chrono::system_clock::now().time_since_epoch())
                                       .count());
    auto stored = database.value_if()->set_enrollment_password_verifier(record);
    sodium_memzero(record.encoded.data(), record.encoded.size());
    if (!stored) {
      return Result<void>::failure(*stored.error_if());
    }
    std::cout << "heyaki-relay --init: enrollment password "
              << (existing_password.value_if()->has_value() && !interactive_password
                      ? "replaced (previously enrolled devices keep working; new "
                        "enrollments need the new password)\n"
                      : "provisioned\n");
  } else {
    std::cout << "heyaki-relay --init: enrollment password already provisioned\n";
  }

  // 4. TURN shared secret (coturn static-auth contract,
  // deploy/coturn/heyaki-turn.env.example).
  std::optional<std::string> turn_secret;
  const auto turn_env_file = config_directory / "heyaki-turn.env";
  if (options.generate_turn_secret) {
    if (regular_file_exists(turn_env_file)) {
      std::cout << "heyaki-relay --init: using existing " << turn_env_file << "\n";
    } else {
      auto generated = generate_turn_secret();
      if (!generated) {
        return Result<void>::failure(*generated.error_if());
      }
      std::ofstream turn_output;
      turn_output.open(turn_env_file, std::ios::binary | std::ios::trunc);
      if (turn_output.is_open()) {
        turn_output << "HEYAKI_TURN_SECRET=" << *generated.value_if() << "\n";
        turn_output.close();
      }
      if (!turn_output || std::filesystem::is_regular_file(turn_env_file) == false) {
        sodium_memzero(generated.value_if()->data(), generated.value_if()->size());
        return Result<void>::failure(init_error(ErrorCode::configuration,
                                                "relay_init_turn_env_write_failed"));
      }
      restrict_owner_permissions(turn_env_file);
      turn_secret = std::move(*generated.value_if());
      std::cout << "heyaki-relay --init: wrote TURN secret " << turn_env_file << "\n";
    }
  }

  // 5. Client access card.
  const std::uint16_t port =
      options.listen_port.has_value() ? *options.listen_port : config.value_if()->listen_port;
  const std::string host{advertised_host(*san_entries.value_if(), options)};
  std::cout << "\n== heyaki relay client access card ==\n"
            << "  URL:     wss://" << host << ":" << port << "\n"
            << "  PIN:     " << hex_encode(*pin.value_if()) << "\n"
            << "  Tenant:  " << config.value_if()->enrollment_default_tenant << "\n"
            << "Share the URL and the enrollment password with devices; the TLS pin\n"
            << "is anchored automatically on first enrollment.\n";
  if (turn_secret.has_value()) {
    std::cout << "\ncoturn needs the same shared secret (deploy/coturn/):\n"
              << "  static-auth-secret=" << *turn_secret << "\n";
  }
  if (options.enrollment_tenant != "default" &&
      options.enrollment_tenant != config.value_if()->enrollment_default_tenant) {
    std::cout << "note: --init-tenant only applies to a newly generated config; the "
                 "existing config keeps enrollment_default_tenant = "
              << config.value_if()->enrollment_default_tenant << "\n";
  }
  return Result<void>::success();
}

}  // namespace heyaki
