if(NOT DEFINED HEYAKI_DEPENDENCY_LOCK OR NOT DEFINED HEYAKI_LICENSE_LOCK OR
   NOT DEFINED HEYAKI_OUTPUT_DIR)
  message(FATAL_ERROR "Dependency lock, license lock, and output directory are required")
endif()

file(STRINGS "${HEYAKI_LICENSE_LOCK}" license_lines)
foreach(line IN LISTS license_lines)
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  endif()
  string(REPLACE "|" ";" fields "${line}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 3)
    message(FATAL_ERROR "Invalid license lock entry: ${line}")
  endif()
  list(GET fields 0 dependency_name)
  list(GET fields 1 license_expression)
  list(GET fields 2 license_path)
  set("license_${dependency_name}" "${license_expression}")
  set("license_path_${dependency_name}" "${license_path}")
endforeach()

file(MAKE_DIRECTORY "${HEYAKI_OUTPUT_DIR}")
set(sbom "SPDXVersion: SPDX-2.3\n")
string(APPEND sbom "DataLicense: CC0-1.0\nSPDXID: SPDXRef-DOCUMENT\n")
string(APPEND sbom "DocumentName: heyaki-third-party\n")
string(APPEND sbom "DocumentNamespace: https://heyaki.invalid/sbom/m0\n")
string(APPEND sbom "Creator: Tool: heyaki-cmake-m0\nCreated: 2026-08-14T00:00:00Z\n\n")
set(manifest "# Heyaki Third-Party Licenses\n\n")
string(APPEND manifest "Generated from `third_party/dependencies.lock` and `third_party/licenses.lock`.\n\n")
string(APPEND manifest "| Dependency | Version/ref | Commit | License | License file |\n")
string(APPEND manifest "| --- | --- | --- | --- | --- |\n")

file(STRINGS "${HEYAKI_DEPENDENCY_LOCK}" dependency_lines)
set(package_count 0)
foreach(line IN LISTS dependency_lines)
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  endif()
  string(REPLACE "|" ";" fields "${line}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 6)
    message(FATAL_ERROR "Invalid dependency lock entry: ${line}")
  endif()
  list(GET fields 0 dependency_name)
  list(GET fields 1 dependency_url)
  list(GET fields 2 dependency_ref)
  list(GET fields 3 dependency_commit)
  if(NOT DEFINED "license_${dependency_name}")
    message(FATAL_ERROR "Missing license metadata for ${dependency_name}")
  endif()
  set(license_expression "${license_${dependency_name}}")
  set(license_path "${license_path_${dependency_name}}")
  math(EXPR package_count "${package_count} + 1")

  string(APPEND sbom "PackageName: ${dependency_name}\n")
  string(APPEND sbom "SPDXID: SPDXRef-Package-${dependency_name}\n")
  string(APPEND sbom "PackageVersion: ${dependency_ref}\n")
  string(APPEND sbom "PackageDownloadLocation: ${dependency_url}\n")
  string(APPEND sbom "PackageChecksum: SHA1: ${dependency_commit}\n")
  string(APPEND sbom "FilesAnalyzed: false\n")
  string(APPEND sbom "PackageLicenseConcluded: ${license_expression}\n")
  string(APPEND sbom "PackageLicenseDeclared: ${license_expression}\n")
  string(APPEND sbom "Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-${dependency_name}\n\n")
  string(APPEND manifest
    "| ${dependency_name} | ${dependency_ref} | `${dependency_commit}` | ${license_expression} | `${license_path}` |\n")
endforeach()

if(NOT package_count EQUAL 9)
  message(FATAL_ERROR "Expected 9 pinned packages, found ${package_count}")
endif()

file(WRITE "${HEYAKI_OUTPUT_DIR}/heyaki.spdx" "${sbom}")
file(WRITE "${HEYAKI_OUTPUT_DIR}/THIRD_PARTY_LICENSES.md" "${manifest}")

