if(NOT DEFINED HEYAKI_DEPENDENCY_LOCK OR
   NOT DEFINED HEYAKI_TRANSITIVE_DEPENDENCY_LOCK OR
   NOT DEFINED HEYAKI_LICENSE_LOCK OR
   NOT DEFINED HEYAKI_SOURCE_DIR OR
   NOT DEFINED HEYAKI_OUTPUT_DIR)
  message(FATAL_ERROR
    "Direct/transitive dependency locks, license lock, source directory, and output directory are required")
endif()

file(STRINGS "${HEYAKI_LICENSE_LOCK}" license_lines)
set(license_names)
foreach(line IN LISTS license_lines)
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  endif()
  string(REPLACE "|" ";" fields "${line}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 3)
    message(FATAL_ERROR "Invalid license lock entry: ${line}")
  endif()
  list(GET fields 0 dependency_name)
  list(GET fields 1 license_expression)
  list(GET fields 2 license_path)
  list(FIND license_names "${dependency_name}" license_index)
  if(NOT license_index EQUAL -1)
    message(FATAL_ERROR "Duplicate license metadata for ${dependency_name}")
  endif()
  if(NOT EXISTS "${HEYAKI_SOURCE_DIR}/${license_path}")
    message(FATAL_ERROR "License file for ${dependency_name} does not exist: ${license_path}")
  endif()
  list(APPEND license_names "${dependency_name}")
  set("license_${dependency_name}" "${license_expression}")
  set("license_path_${dependency_name}" "${license_path}")
endforeach()

file(MAKE_DIRECTORY "${HEYAKI_OUTPUT_DIR}")
set(sbom "SPDXVersion: SPDX-2.3\n")
string(APPEND sbom "DataLicense: CC0-1.0\nSPDXID: SPDXRef-DOCUMENT\n")
string(APPEND sbom "DocumentName: heyaki-third-party\n")
string(APPEND sbom "DocumentNamespace: https://heyaki.invalid/sbom/m0\n")
string(APPEND sbom "Creator: Tool: heyaki-cmake-m0\nCreated: 2026-08-14T00:00:00Z\n\n")
set(manifest "# Heyaki Third-Party Licenses\n\n")
string(APPEND manifest "Generated from `third_party/dependencies.lock` and `third_party/licenses.lock`.\n\n")
string(APPEND manifest
  "Transitive submodules are pinned by `third_party/transitive-dependencies.lock`.\n\n")
string(APPEND manifest "| Dependency | Scope | Version/ref | Commit | License | License file |\n")
string(APPEND manifest "| --- | --- | --- | --- | --- | --- |\n")

set(package_names)
macro(heyaki_append_package package_name package_version package_url package_commit package_scope)
  list(FIND package_names "${package_name}" package_index)
  if(NOT package_index EQUAL -1)
    message(FATAL_ERROR "Duplicate package metadata for ${package_name}")
  endif()
  if(NOT DEFINED "license_${package_name}")
    message(FATAL_ERROR "Missing license metadata for ${package_name}")
  endif()
  string(LENGTH "${package_commit}" package_commit_length)
  if(NOT package_commit_length EQUAL 40 OR
     NOT "${package_commit}" MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Invalid commit for ${package_name}: ${package_commit}")
  endif()

  set(license_expression "${license_${package_name}}")
  set(license_path "${license_path_${package_name}}")
  list(APPEND package_names "${package_name}")

  string(APPEND sbom "PackageName: ${package_name}\n")
  string(APPEND sbom "SPDXID: SPDXRef-Package-${package_name}\n")
  string(APPEND sbom "PackageVersion: ${package_version}\n")
  string(APPEND sbom "PackageDownloadLocation: ${package_url}\n")
  string(APPEND sbom "PackageChecksum: SHA1: ${package_commit}\n")
  string(APPEND sbom "FilesAnalyzed: false\n")
  string(APPEND sbom "PackageLicenseConcluded: ${license_expression}\n")
  string(APPEND sbom "PackageLicenseDeclared: ${license_expression}\n")
  string(APPEND sbom
    "Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-${package_name}\n\n")
  string(APPEND manifest
    "| ${package_name} | ${package_scope} | ${package_version} | `${package_commit}` | ${license_expression} | `${license_path}` |\n")
endmacro()

file(STRINGS "${HEYAKI_DEPENDENCY_LOCK}" dependency_lines)
set(direct_package_names)
foreach(line IN LISTS dependency_lines)
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  endif()
  string(REPLACE "|" ";" fields "${line}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 6)
    message(FATAL_ERROR "Invalid dependency lock entry: ${line}")
  endif()
  list(GET fields 0 dependency_name)
  list(GET fields 1 dependency_url)
  list(GET fields 2 dependency_ref)
  list(GET fields 3 dependency_commit)
  list(APPEND direct_package_names "${dependency_name}")
  heyaki_append_package(
    "${dependency_name}" "${dependency_ref}" "${dependency_url}" "${dependency_commit}" "direct")
endforeach()

list(LENGTH direct_package_names direct_package_count)
if(NOT direct_package_count EQUAL 10)
  message(FATAL_ERROR "Expected 10 direct pinned packages, found ${direct_package_count}")
endif()

file(STRINGS "${HEYAKI_TRANSITIVE_DEPENDENCY_LOCK}" transitive_lines)
set(transitive_package_count 0)
foreach(line IN LISTS transitive_lines)
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  endif()
  string(REPLACE "|" ";" fields "${line}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 5)
    message(FATAL_ERROR "Invalid transitive dependency lock entry: ${line}")
  endif()
  list(GET fields 0 parent_name)
  list(GET fields 1 dependency_name)
  list(GET fields 3 dependency_url)
  list(GET fields 4 dependency_commit)
  list(FIND direct_package_names "${parent_name}" parent_index)
  if(parent_index EQUAL -1)
    message(FATAL_ERROR "Unknown direct parent ${parent_name} for ${dependency_name}")
  endif()
  heyaki_append_package(
    "${dependency_name}" "${dependency_commit}" "${dependency_url}" "${dependency_commit}"
    "submodule of `${parent_name}`")
  string(APPEND sbom
    "Relationship: SPDXRef-Package-${parent_name} DEPENDS_ON SPDXRef-Package-${dependency_name}\n\n")
  math(EXPR transitive_package_count "${transitive_package_count} + 1")
endforeach()

if(NOT transitive_package_count EQUAL 5)
  message(FATAL_ERROR
    "Expected 5 transitive pinned packages, found ${transitive_package_count}")
endif()

list(LENGTH package_names package_count)
list(LENGTH license_names license_count)
if(NOT package_count EQUAL license_count)
  message(FATAL_ERROR
    "Expected one license record per package, found ${package_count} packages and ${license_count} licenses")
endif()

file(WRITE "${HEYAKI_OUTPUT_DIR}/heyaki.spdx" "${sbom}")
file(WRITE "${HEYAKI_OUTPUT_DIR}/THIRD_PARTY_LICENSES.md" "${manifest}")
